trigger:
  branches:
    include:
      - master  # or main

pool:
  name: Default

variables:
  azureSubscription: 'Nishad_Demo_SC'
  webAppName: 'testapp1'
  nodeVersion: '18.x'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'npm install and build'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
              replaceExistingArchive: true
            displayName: 'Archive build output'

          - publish: '$(Build.ArtifactStagingDirectory)/app.zip'
            artifact: drop

  - stage: Test
    displayName: Test Stage
    dependsOn: Build
    jobs:
      - job: Test
        steps:
          - script: |
              npm test
            displayName: 'Run Tests'

  - stage: Deploy
    displayName: Deploy Stage
    dependsOn: Test
    jobs:
      - deployment: DeployWeb
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(webAppName)
                    package: '$(Pipeline.Workspace)/drop/app.zip'
